// ============================================================================
// Purp → Rust Codegen — The Solana Coding Language
// Generates Anchor-compatible Rust code from Purp AST
// ============================================================================

import * as AST from '../../ast/index.js';

export class RustCodegen {
  private output: string[] = [];
  private indent: number = 0;

  generate(program: AST.ProgramNode): string {
    this.output = [];
    this.emitPrelude();

    for (const node of program.body) {
      this.emitTopLevel(node);
    }

    return this.output.join('\n');
  }

  private emitPrelude(): void {
    this.writeln('// AUTO-GENERATED by Purp Compiler v0.1.0');
    this.writeln('// Do not edit this file directly. Edit the .purp source instead.');
    this.writeln('');
    this.writeln('use anchor_lang::prelude::*;');
    this.writeln('');
  }

  private emitTopLevel(node: AST.TopLevelNode): void {
    switch (node.kind) {
      case 'ProgramDeclaration': return this.emitProgram(node);
      case 'InstructionDeclaration': return this.emitInstruction(node);
      case 'AccountDeclaration': return this.emitAccount(node);
      case 'StructDeclaration': return this.emitStruct(node);
      case 'EnumDeclaration': return this.emitEnum(node);
      case 'FunctionDeclaration': return this.emitFunction(node);
      case 'EventDeclaration': return this.emitEvent(node);
      case 'ErrorDeclaration': return this.emitError(node);
      case 'ConstDeclaration': return this.emitConst(node);
      case 'ImportDeclaration': return this.emitImport(node);
      default:
        this.writeln(`// TODO: codegen for ${node.kind}`);
    }
  }

  // === Program ===

  private emitProgram(node: AST.ProgramDeclaration): void {
    if (node.id) {
      this.writeln(`declare_id!("${node.id}");`);
    } else {
      this.writeln('declare_id!("11111111111111111111111111111111");');
    }
    this.writeln('');
    this.writeln('#[program]');
    this.writeln(`pub mod ${this.toSnakeCase(node.name)} {`);
    this.indentIn();
    this.writeln('use super::*;');
    this.writeln('');
    for (const child of node.body) {
      this.emitTopLevel(child);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Instruction ===

  private emitInstruction(node: AST.InstructionDeclaration): void {
    const params = node.params.map(p => `${p.name}: ${this.typeToRust(p.type)}`).join(', ');
    const ctxType = `Context<${this.toPascalCase(node.name)}Accounts>`;
    const allParams = params ? `ctx: ${ctxType}, ${params}` : `ctx: ${ctxType}`;
    const returnType = node.returns ? this.typeToRust(node.returns) : 'Result<()>';

    this.writeln(`pub fn ${this.toSnakeCase(node.name)}(${allParams}) -> ${returnType} {`);
    this.indentIn();
    this.emitStatements(node.body);
    if (!this.lastLineHasReturn(node.body)) {
      this.writeln('Ok(())');
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');

    // Generate accounts struct
    this.emitAccountsStruct(node);
  }

  private emitAccountsStruct(node: AST.InstructionDeclaration): void {
    this.writeln('#[derive(Accounts)]');
    this.writeln(`pub struct ${this.toPascalCase(node.name)}Accounts<'info> {`);
    this.indentIn();
    for (const acc of node.accounts) {
      this.emitAccountField(acc);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  private emitAccountField(acc: AST.AccountParam): void {
    const constraints: string[] = [];
    const type = acc.accountType;

    if (type.kind === 'Signer') {
      if (type.mutable) constraints.push('mut');
      this.writeln(`#[account(${constraints.join(', ')})]`);
      this.writeln(`pub ${acc.name}: Signer<'info>,`);
    } else if (type.kind === 'Account') {
      if (type.mutable) constraints.push('mut');
      this.writeln(`#[account(${constraints.join(', ')})]`);
      this.writeln(`pub ${acc.name}: Account<'info, ${type.type}>,`);
    } else if (type.kind === 'PDA') {
      if (type.mutable) constraints.push('mut');
      this.writeln(`#[account(${constraints.join(', ')})]`);
      this.writeln(`pub ${acc.name}: Account<'info, PdaAccount>,`);
    } else if (type.kind === 'Mint') {
      if (type.mutable) constraints.push('mut');
      this.writeln(`#[account(${constraints.join(', ')})]`);
      this.writeln(`pub ${acc.name}: Account<'info, Mint>,`);
    } else if (type.kind === 'TokenAccount') {
      if (type.mutable) constraints.push('mut');
      this.writeln(`#[account(${constraints.join(', ')})]`);
      this.writeln(`pub ${acc.name}: Account<'info, TokenAccount>,`);
    } else if (type.kind === 'Program') {
      this.writeln(`pub ${acc.name}: Program<'info, ${type.name}>,`);
    } else {
      if (type.mutable) constraints.push('mut');
      this.writeln(`#[account(${constraints.join(', ')})]`);
      this.writeln(`pub ${acc.name}: AccountInfo<'info>,`);
    }
  }

  // === Account ===

  private emitAccount(node: AST.AccountDeclaration): void {
    this.writeln('#[account]');
    this.writeln(`pub struct ${node.name} {`);
    this.indentIn();
    for (const field of node.fields) {
      this.writeln(`pub ${field.name}: ${this.typeToRust(field.type)},`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Struct ===

  private emitStruct(node: AST.StructDeclaration): void {
    this.writeln('#[derive(AnchorSerialize, AnchorDeserialize, Clone)]');
    this.writeln(`pub struct ${node.name} {`);
    this.indentIn();
    for (const field of node.fields) {
      this.writeln(`pub ${field.name}: ${this.typeToRust(field.type)},`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Enum ===

  private emitEnum(node: AST.EnumDeclaration): void {
    this.writeln('#[derive(AnchorSerialize, AnchorDeserialize, Clone, PartialEq)]');
    this.writeln(`pub enum ${node.name} {`);
    this.indentIn();
    for (const variant of node.variants) {
      if (variant.fields && variant.fields.length > 0) {
        const fields = variant.fields.map(f => `${f.name}: ${this.typeToRust(f.type)}`).join(', ');
        this.writeln(`${variant.name} { ${fields} },`);
      } else {
        this.writeln(`${variant.name},`);
      }
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Function ===

  private emitFunction(node: AST.FunctionDeclaration): void {
    const vis = node.visibility === 'pub' ? 'pub ' : '';
    const params = node.params.map(p => `${p.name}: ${this.typeToRust(p.type)}`).join(', ');
    const ret = node.returnType ? ` -> ${this.typeToRust(node.returnType)}` : '';
    this.writeln(`${vis}fn ${this.toSnakeCase(node.name)}(${params})${ret} {`);
    this.indentIn();
    this.emitStatements(node.body);
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Event ===

  private emitEvent(node: AST.EventDeclaration): void {
    this.writeln('#[event]');
    this.writeln(`pub struct ${node.name} {`);
    this.indentIn();
    for (const field of node.fields) {
      this.writeln(`pub ${field.name}: ${this.typeToRust(field.type)},`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Error ===

  private emitError(node: AST.ErrorDeclaration): void {
    this.writeln('#[error_code]');
    this.writeln(`pub enum ${node.name} {`);
    this.indentIn();
    for (const variant of node.variants) {
      this.writeln(`#[msg("${variant.message}")]`);
      this.writeln(`${variant.name},`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Const ===

  private emitConst(node: AST.ConstDeclaration): void {
    const vis = node.visibility === 'pub' ? 'pub ' : '';
    const ty = node.type ? `: ${this.typeToRust(node.type)}` : '';
    this.writeln(`${vis}const ${node.name.toUpperCase()}${ty} = ${this.exprToRust(node.value)};`);
  }

  // === Import ===

  private emitImport(node: AST.ImportDeclaration): void {
    if (node.isWildcard) {
      this.writeln(`use ${node.path.replace(/\//g, '::')}::*;`);
    } else if (node.items.length > 0) {
      const items = node.items.map(i => i.alias ? `${i.name} as ${i.alias}` : i.name).join(', ');
      this.writeln(`use ${node.path.replace(/\//g, '::')}::{${items}};`);
    } else {
      this.writeln(`use ${node.path.replace(/\//g, '::')};`);
    }
  }

  // === Statements ===

  private emitStatements(stmts: AST.Statement[]): void {
    for (const stmt of stmts) {
      this.emitStatement(stmt);
    }
  }

  private emitStatement(stmt: AST.Statement): void {
    switch (stmt.kind) {
      case 'LetStatement': {
        const mutStr = stmt.mutable ? 'mut ' : '';
        const ty = stmt.type ? `: ${this.typeToRust(stmt.type)}` : '';
        const val = stmt.value ? ` = ${this.exprToRust(stmt.value)}` : '';
        this.writeln(`let ${mutStr}${stmt.name}${ty}${val};`);
        break;
      }
      case 'ConstStatement': {
        const ty = stmt.type ? `: ${this.typeToRust(stmt.type)}` : '';
        this.writeln(`const ${stmt.name.toUpperCase()}${ty} = ${this.exprToRust(stmt.value)};`);
        break;
      }
      case 'AssignmentStatement': {
        this.writeln(`${this.exprToRust(stmt.target)} ${stmt.operator} ${this.exprToRust(stmt.value)};`);
        break;
      }
      case 'ReturnStatement': {
        if (stmt.value) {
          this.writeln(`return ${this.exprToRust(stmt.value)};`);
        } else {
          this.writeln('return;');
        }
        break;
      }
      case 'IfStatement': {
        this.writeln(`if ${this.exprToRust(stmt.condition)} {`);
        this.indentIn();
        this.emitStatements(stmt.then);
        this.indentOut();
        if (stmt.elseIf) {
          for (const ei of stmt.elseIf) {
            this.writeln(`} else if ${this.exprToRust(ei.condition)} {`);
            this.indentIn();
            this.emitStatements(ei.body);
            this.indentOut();
          }
        }
        if (stmt.else) {
          this.writeln('} else {');
          this.indentIn();
          this.emitStatements(stmt.else);
          this.indentOut();
        }
        this.writeln('}');
        break;
      }
      case 'ForStatement': {
        this.writeln(`for ${stmt.variable} in ${this.exprToRust(stmt.iterable)} {`);
        this.indentIn();
        this.emitStatements(stmt.body);
        this.indentOut();
        this.writeln('}');
        break;
      }
      case 'WhileStatement': {
        this.writeln(`while ${this.exprToRust(stmt.condition)} {`);
        this.indentIn();
        this.emitStatements(stmt.body);
        this.indentOut();
        this.writeln('}');
        break;
      }
      case 'LoopStatement': {
        this.writeln('loop {');
        this.indentIn();
        this.emitStatements(stmt.body);
        this.indentOut();
        this.writeln('}');
        break;
      }
      case 'BreakStatement': this.writeln('break;'); break;
      case 'ContinueStatement': this.writeln('continue;'); break;
      case 'EmitStatement': {
        this.writeln(`emit!(${stmt.event} {`);
        this.indentIn();
        // Emit args as fields (simplified)
        for (const arg of stmt.args) {
          this.writeln(`${this.exprToRust(arg)},`);
        }
        this.indentOut();
        this.writeln('});');
        break;
      }
      case 'ExpressionStatement': {
        this.writeln(`${this.exprToRust(stmt.expression)};`);
        break;
      }
      default:
        this.writeln(`// TODO: statement ${stmt.kind}`);
    }
  }

  // === Expressions ===

  private exprToRust(expr: AST.Expression): string {
    switch (expr.kind) {
      case 'NumberLiteral': return expr.raw;
      case 'StringLiteral': return `"${expr.value}"`;
      case 'BooleanLiteral': return expr.value ? 'true' : 'false';
      case 'NullLiteral': return 'None';
      case 'IdentifierExpr': return expr.name;
      case 'BinaryExpr': return `(${this.exprToRust(expr.left)} ${expr.operator} ${this.exprToRust(expr.right)})`;
      case 'UnaryExpr': return `${expr.operator}${this.exprToRust(expr.operand)}`;
      case 'CallExpr': {
        const args = expr.args.map(a => this.exprToRust(a)).join(', ');
        return `${this.exprToRust(expr.callee)}(${args})`;
      }
      case 'MemberExpr': return `${this.exprToRust(expr.object)}.${expr.property}`;
      case 'IndexExpr': return `${this.exprToRust(expr.object)}[${this.exprToRust(expr.index)}]`;
      case 'ArrayExpr': {
        const elems = expr.elements.map(e => this.exprToRust(e)).join(', ');
        return `vec![${elems}]`;
      }
      case 'StructInitExpr': {
        const fields = expr.fields.map(f => `${f.name}: ${this.exprToRust(f.value)}`).join(', ');
        return `${expr.name} { ${fields} }`;
      }
      case 'AwaitExpr': return `${this.exprToRust(expr.expression)}`;
      case 'SolLiteral': return `${expr.amount * 1_000_000_000}`;
      case 'LamportsLiteral': return `${expr.amount}`;
      default: return `/* TODO: expr ${expr.kind} */`;
    }
  }

  // === Type Mapping ===

  private typeToRust(type: AST.TypeAnnotation): string {
    switch (type.kind) {
      case 'PrimitiveType': {
        const map: Record<string, string> = {
          'u8': 'u8', 'u16': 'u16', 'u32': 'u32', 'u64': 'u64', 'u128': 'u128',
          'i8': 'i8', 'i16': 'i16', 'i32': 'i32', 'i64': 'i64', 'i128': 'i128',
          'f32': 'f32', 'f64': 'f64', 'bool': 'bool', 'string': 'String',
          'pubkey': 'Pubkey', 'bytes': 'Vec<u8>',
        };
        return map[type.name] ?? type.name;
      }
      case 'NamedType': {
        if (type.typeArgs && type.typeArgs.length > 0) {
          const args = type.typeArgs.map(a => this.typeToRust(a)).join(', ');
          return `${type.name}<${args}>`;
        }
        return type.name;
      }
      case 'ArrayType': {
        if (type.size !== undefined) {
          return `[${this.typeToRust(type.element)}; ${type.size}]`;
        }
        return `Vec<${this.typeToRust(type.element)}>`;
      }
      case 'OptionType': return `Option<${this.typeToRust(type.inner)}>`;
      case 'TupleType': {
        const elems = type.elements.map(e => this.typeToRust(e)).join(', ');
        return `(${elems})`;
      }
      default: return 'unknown';
    }
  }

  // === Utility ===

  private lastLineHasReturn(stmts: AST.Statement[]): boolean {
    if (stmts.length === 0) return false;
    return stmts[stmts.length - 1].kind === 'ReturnStatement';
  }

  private toSnakeCase(s: string): string {
    return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
  }

  private toPascalCase(s: string): string {
    return s.replace(/(^|_)([a-z])/g, (_m, _p1, p2) => p2.toUpperCase());
  }

  private writeln(line: string): void {
    const indentStr = '    '.repeat(this.indent);
    this.output.push(`${indentStr}${line}`);
  }

  private indentIn(): void { this.indent++; }
  private indentOut(): void { this.indent = Math.max(0, this.indent - 1); }
}
