// ============================================================================
// Purp TypeScript Code Generator v0.2.0 — The Solana Coding Language
// Generates Anchor-compatible TypeScript client SDK
// Complete with: IDL types, instruction methods, account fetchers,
// event listeners, error parsing, generics, tuples, template literals
// ============================================================================

import * as AST from '../../ast/index.js';

export class TypeScriptCodegen {
  private output: string[] = [];
  private indent: number = 0;
  private programName: string = '';
  private accounts: AST.AccountDeclaration[] = [];
  private instructions: AST.InstructionDeclaration[] = [];
  private events: AST.EventDeclaration[] = [];
  private errors: AST.ErrorDeclaration[] = [];
  private structs: AST.StructDeclaration[] = [];
  private enums: AST.EnumDeclaration[] = [];

  generate(program: AST.ProgramNode): string {
    this.output = [];
    this.collectDeclarations(program.body);
    this.emitHeader();
    this.emitTypes();
    this.emitClientClass();
    this.emitEventTypes();
    this.emitErrorTypes();
    return this.output.join('\n');
  }

  private collectDeclarations(nodes: AST.TopLevelNode[]): void {
    for (const node of nodes) {
      switch (node.kind) {
        case 'ProgramDeclaration':
          this.programName = node.name;
          this.collectDeclarations(node.body);
          break;
        case 'AccountDeclaration':
          this.accounts.push(node);
          break;
        case 'InstructionDeclaration':
          this.instructions.push(node);
          break;
        case 'EventDeclaration':
          this.events.push(node);
          break;
        case 'ErrorDeclaration':
          this.errors.push(node);
          break;
        case 'StructDeclaration':
          this.structs.push(node);
          break;
        case 'EnumDeclaration':
          this.enums.push(node);
          break;
      }
    }
  }

  // =========================================================================
  // Header
  // =========================================================================

  private emitHeader(): void {
    this.emit('// Auto-generated by Purp SCL Compiler v0.2.0');
    this.emit('// Do not edit manually');
    this.emit('');
    this.emit("import { PublicKey, Connection, Transaction, TransactionInstruction, SystemProgram, Keypair, LAMPORTS_PER_SOL } from '@solana/web3.js';");
    this.emit("import { Program, AnchorProvider, BN, web3, Idl } from '@coral-xyz/anchor';");
    this.emit("import { TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID, getAssociatedTokenAddress } from '@solana/spl-token';");
    this.emit('');
  }

  // =========================================================================
  // Type Interfaces
  // =========================================================================

  private emitTypes(): void {
    this.emit('// ═══════════════════════════════════════════════════════');
    this.emit('// Account Types');
    this.emit('// ═══════════════════════════════════════════════════════');
    this.emit('');

    for (const acc of this.accounts) {
      this.emitInterface(acc.name, acc.fields);
    }

    for (const struct of this.structs) {
      this.emitStructInterface(struct);
    }

    for (const enumDecl of this.enums) {
      this.emitEnumType(enumDecl);
    }

    this.emit('');
  }

  private emitInterface(name: string, fields: AST.FieldDeclaration[]): void {
    this.emit(`export interface ${name} {`);
    this.indent++;
    for (const field of fields) {
      this.emit(`${this.toCamelCase(field.name)}: ${this.emitTypeStr(field.type)};`);
    }
    this.indent--;
    this.emit('}');
    this.emit('');
  }

  private emitStructInterface(node: AST.StructDeclaration): void {
    const generics = node.genericParams && node.genericParams.length > 0
      ? `<${node.genericParams.map(g => g.name).join(', ')}>`
      : '';
    this.emit(`export interface ${node.name}${generics} {`);
    this.indent++;
    for (const field of node.fields) {
      this.emit(`${this.toCamelCase(field.name)}: ${this.emitTypeStr(field.type)};`);
    }
    this.indent--;
    this.emit('}');
    this.emit('');
  }

  private emitEnumType(node: AST.EnumDeclaration): void {
    const generics = node.genericParams && node.genericParams.length > 0
      ? `<${node.genericParams.map(g => g.name).join(', ')}>`
      : '';

    // Emit as discriminated union or simple enum
    const hasFields = node.variants.some(v => v.fields && v.fields.length > 0);
    if (hasFields) {
      this.emit(`export type ${node.name}${generics} =`);
      this.indent++;
      for (let i = 0; i < node.variants.length; i++) {
        const v = node.variants[i];
        const sep = i < node.variants.length - 1 ? ' |' : ';';
        if (v.fields && v.fields.length > 0) {
          const fields = v.fields.map(f => `${this.toCamelCase(f.name)}: ${this.emitTypeStr(f.type)}`).join('; ');
          this.emit(`{ kind: '${v.name}'; ${fields} }${sep}`);
        } else {
          this.emit(`{ kind: '${v.name}' }${sep}`);
        }
      }
      this.indent--;
    } else {
      this.emit(`export enum ${node.name} {`);
      this.indent++;
      for (const v of node.variants) {
        this.emit(`${v.name},`);
      }
      this.indent--;
      this.emit('}');
    }
    this.emit('');
  }

  // =========================================================================
  // Client Class
  // =========================================================================

  private emitClientClass(): void {
    const className = this.programName || 'PurpProgram';
    this.emit('// ═══════════════════════════════════════════════════════');
    this.emit('// Client SDK');
    this.emit('// ═══════════════════════════════════════════════════════');
    this.emit('');
    this.emit(`export class ${className}Client {`);
    this.indent++;
    this.emit('private program: Program;');
    this.emit('private provider: AnchorProvider;');
    this.emit('');

    // Constructor
    this.emit('constructor(program: Program, provider: AnchorProvider) {');
    this.indent++;
    this.emit('this.program = program;');
    this.emit('this.provider = provider;');
    this.indent--;
    this.emit('}');
    this.emit('');

    // Static factory
    this.emit(`static create(programId: PublicKey, provider: AnchorProvider, idl: Idl): ${className}Client {`);
    this.indent++;
    this.emit('const program = new Program(idl, programId, provider);');
    this.emit(`return new ${className}Client(program, provider);`);
    this.indent--;
    this.emit('}');
    this.emit('');

    // Instruction methods
    for (const instr of this.instructions) {
      this.emitInstructionMethod(instr);
    }

    // Account fetchers
    for (const acc of this.accounts) {
      this.emitAccountFetcher(acc);
    }

    // Event listeners
    if (this.events.length > 0) {
      this.emitEventListener();
    }

    // PDA helpers
    this.emitPDAHelpers();

    this.indent--;
    this.emit('}');
    this.emit('');
  }

  private emitInstructionMethod(node: AST.InstructionDeclaration): void {
    const methodName = this.toCamelCase(node.name);
    const accountParams = node.accounts.map(a =>
      `${this.toCamelCase(a.name)}: PublicKey`
    );
    const valueParams = node.params.map(p =>
      `${this.toCamelCase(p.name)}: ${this.emitTypeStr(p.type)}`
    );
    const allParams = [...accountParams, ...valueParams];

    this.emit(`async ${methodName}(`);
    this.indent++;
    for (let i = 0; i < allParams.length; i++) {
      this.emit(`${allParams[i]}${i < allParams.length - 1 ? ',' : ''}`);
    }
    this.indent--;
    this.emit('): Promise<string> {');
    this.indent++;

    // Build accounts object
    this.emit('const accounts = {');
    this.indent++;
    for (const acc of node.accounts) {
      const accName = this.toCamelCase(acc.name);
      if (acc.accountType.kind === 'Program') {
        if (acc.accountType.name === 'System') {
          this.emit(`${accName}: SystemProgram.programId,`);
        } else if (acc.accountType.name === 'Token') {
          this.emit(`${accName}: TOKEN_PROGRAM_ID,`);
        } else {
          this.emit(`${accName}: ${accName},`);
        }
      } else {
        this.emit(`${accName}: ${accName},`);
      }
    }
    this.indent--;
    this.emit('};');
    this.emit('');

    // Build args
    const argNames = node.params.map(p => this.toCamelCase(p.name));
    const argsStr = argNames.length > 0 ? argNames.join(', ') : '';

    this.emit(`const tx = await this.program.methods.${this.toCamelCase(node.name)}(${argsStr})`);
    this.indent++;
    this.emit('.accounts(accounts)');
    this.emit('.rpc();');
    this.indent--;
    this.emit('');
    this.emit('return tx;');

    this.indent--;
    this.emit('}');
    this.emit('');
  }

  private emitAccountFetcher(acc: AST.AccountDeclaration): void {
    const methodName = `fetch${acc.name}`;
    this.emit(`async ${methodName}(address: PublicKey): Promise<${acc.name} | null> {`);
    this.indent++;
    this.emit('try {');
    this.indent++;
    this.emit(`const account = await (this.program.account as any).${this.toCamelCase(acc.name)}.fetch(address);`);
    this.emit('return account as unknown as ' + acc.name + ';');
    this.indent--;
    this.emit('} catch {');
    this.indent++;
    this.emit('return null;');
    this.indent--;
    this.emit('}');
    this.indent--;
    this.emit('}');
    this.emit('');

    // Fetch all
    this.emit(`async fetchAll${acc.name}s(): Promise<{ publicKey: PublicKey; account: ${acc.name} }[]> {`);
    this.indent++;
    this.emit(`const accounts = await (this.program.account as any).${this.toCamelCase(acc.name)}.all();`);
    this.emit(`return accounts.map((a: any) => ({ publicKey: a.publicKey, account: a.account as ${acc.name} }));`);
    this.indent--;
    this.emit('}');
    this.emit('');
  }

  private emitEventListener(): void {
    this.emit('addEventListener<T extends string>(');
    this.indent++;
    this.emit('eventName: T,');
    this.emit('callback: (event: any, slot: number) => void');
    this.indent--;
    this.emit('): number {');
    this.indent++;
    this.emit('return this.program.addEventListener(eventName, callback);');
    this.indent--;
    this.emit('}');
    this.emit('');

    this.emit('async removeEventListener(listenerId: number): Promise<void> {');
    this.indent++;
    this.emit('await this.program.removeEventListener(listenerId);');
    this.indent--;
    this.emit('}');
    this.emit('');
  }

  private emitPDAHelpers(): void {
    this.emit('async findPDA(seeds: (Buffer | Uint8Array)[], programId?: PublicKey): Promise<[PublicKey, number]> {');
    this.indent++;
    this.emit('return PublicKey.findProgramAddress(seeds, programId ?? this.program.programId);');
    this.indent--;
    this.emit('}');
    this.emit('');

    this.emit('async getAssociatedTokenAddress(mint: PublicKey, owner: PublicKey): Promise<PublicKey> {');
    this.indent++;
    this.emit('return getAssociatedTokenAddress(mint, owner);');
    this.indent--;
    this.emit('}');
    this.emit('');
  }

  // =========================================================================
  // Event Types
  // =========================================================================

  private emitEventTypes(): void {
    if (this.events.length === 0) return;

    this.emit('// ═══════════════════════════════════════════════════════');
    this.emit('// Event Types');
    this.emit('// ═══════════════════════════════════════════════════════');
    this.emit('');

    for (const event of this.events) {
      this.emit(`export interface ${event.name}Event {`);
      this.indent++;
      for (const field of event.fields) {
        this.emit(`${this.toCamelCase(field.name)}: ${this.emitTypeStr(field.type)};`);
      }
      this.indent--;
      this.emit('}');
      this.emit('');
    }
  }

  // =========================================================================
  // Error Types
  // =========================================================================

  private emitErrorTypes(): void {
    if (this.errors.length === 0) return;

    this.emit('// ═══════════════════════════════════════════════════════');
    this.emit('// Error Codes');
    this.emit('// ═══════════════════════════════════════════════════════');
    this.emit('');

    for (const err of this.errors) {
      this.emit(`export enum ${err.name}ErrorCode {`);
      this.indent++;
      for (const variant of err.variants) {
        this.emit(`${variant.name} = ${variant.code},`);
      }
      this.indent--;
      this.emit('}');
      this.emit('');

      this.emit(`export const ${err.name}Messages: Record<number, string> = {`);
      this.indent++;
      for (const variant of err.variants) {
        this.emit(`[${variant.code}]: "${variant.message}",`);
      }
      this.indent--;
      this.emit('};');
      this.emit('');

      // Error parser helper
      this.emit(`export function parse${err.name}Error(error: any): { code: number; message: string } | null {`);
      this.indent++;
      this.emit('if (error?.error?.errorCode?.number) {');
      this.indent++;
      this.emit(`const code = error.error.errorCode.number;`);
      this.emit(`const message = ${err.name}Messages[code] ?? 'Unknown error';`);
      this.emit('return { code, message };');
      this.indent--;
      this.emit('}');
      this.emit('return null;');
      this.indent--;
      this.emit('}');
      this.emit('');
    }
  }

  // =========================================================================
  // Type Mapping
  // =========================================================================

  emitTypeStr(type: AST.TypeAnnotation): string {
    switch (type.kind) {
      case 'PrimitiveType':
        return this.mapPrimitiveType(type.name);
      case 'NamedType': {
        const typeArgs = type.typeArgs && type.typeArgs.length > 0
          ? `<${type.typeArgs.map(a => this.emitTypeStr(a)).join(', ')}>`
          : '';
        return `${type.name}${typeArgs}`;
      }
      case 'ArrayType':
        return `${this.emitTypeStr(type.element)}[]`;
      case 'OptionType':
        return `${this.emitTypeStr(type.inner)} | null`;
      case 'ResultType': {
        const ok = this.emitTypeStr(type.ok);
        const err = type.err ? this.emitTypeStr(type.err) : 'Error';
        return `{ ok: ${ok} } | { err: ${err} }`;
      }
      case 'TupleType':
        return `[${type.elements.map(e => this.emitTypeStr(e)).join(', ')}]`;
      case 'FunctionType':
        return `(${type.params.map((p, i) => `arg${i}: ${this.emitTypeStr(p)}`).join(', ')}) => ${this.emitTypeStr(type.returnType)}`;
      case 'GenericType':
        return `${type.name}<${type.typeParams.map(p => this.emitTypeStr(p)).join(', ')}>`;
    }
  }

  private mapPrimitiveType(name: string): string {
    const map: Record<string, string> = {
      'u8': 'number',
      'u16': 'number',
      'u32': 'number',
      'u64': 'BN',
      'u128': 'BN',
      'i8': 'number',
      'i16': 'number',
      'i32': 'number',
      'i64': 'BN',
      'i128': 'BN',
      'f32': 'number',
      'f64': 'number',
      'bool': 'boolean',
      'string': 'string',
      'pubkey': 'PublicKey',
      'bytes': 'Buffer',
    };
    return map[name] ?? name;
  }

  // =========================================================================
  // Helpers
  // =========================================================================

  private emit(line: string): void {
    const indentation = '  '.repeat(this.indent);
    this.output.push(`${indentation}${line}`);
  }

  private toCamelCase(name: string): string {
    return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
  }
}
