// ============================================================================
// Purp → TypeScript Codegen — The Solana Coding Language
// Generates TypeScript SDK / client code from Purp AST
// ============================================================================

import * as AST from '../../ast/index.js';

export class TypeScriptCodegen {
  private output: string[] = [];
  private indent: number = 0;

  generate(program: AST.ProgramNode): string {
    this.output = [];
    this.emitPrelude();

    for (const node of program.body) {
      this.emitTopLevel(node);
    }

    return this.output.join('\n');
  }

  private emitPrelude(): void {
    this.writeln('// AUTO-GENERATED by Purp Compiler v0.1.0');
    this.writeln('// Do not edit this file directly. Edit the .purp source instead.');
    this.writeln('');
    this.writeln("import { Connection, PublicKey, Transaction, SystemProgram, Keypair } from '@solana/web3.js';");
    this.writeln("import { Program, AnchorProvider, BN } from '@coral-xyz/anchor';");
    this.writeln('');
  }

  private emitTopLevel(node: AST.TopLevelNode): void {
    switch (node.kind) {
      case 'ProgramDeclaration': return this.emitProgram(node);
      case 'InstructionDeclaration': return this.emitInstructionClient(node);
      case 'AccountDeclaration': return this.emitAccountInterface(node);
      case 'StructDeclaration': return this.emitInterface(node);
      case 'EnumDeclaration': return this.emitTypeEnum(node);
      case 'FunctionDeclaration': return this.emitFunction(node);
      case 'EventDeclaration': return this.emitEventInterface(node);
      case 'ErrorDeclaration': return this.emitErrorEnum(node);
      case 'ConstDeclaration': return this.emitConst(node);
      case 'ClientBlock': return this.emitClientBlock(node);
      default:
        this.writeln(`// TODO: codegen for ${node.kind}`);
    }
  }

  // === Program ===

  private emitProgram(node: AST.ProgramDeclaration): void {
    const programId = node.id ?? '11111111111111111111111111111111';
    this.writeln(`export const PROGRAM_ID = new PublicKey('${programId}');`);
    this.writeln('');
    this.writeln(`export class ${this.toPascalCase(node.name)}Client {`);
    this.indentIn();
    this.writeln('private program: Program;');
    this.writeln('private connection: Connection;');
    this.writeln('');
    this.writeln('constructor(program: Program, connection: Connection) {');
    this.indentIn();
    this.writeln('this.program = program;');
    this.writeln('this.connection = connection;');
    this.indentOut();
    this.writeln('}');
    this.writeln('');

    for (const child of node.body) {
      if (child.kind === 'InstructionDeclaration') {
        this.emitInstructionMethod(child);
      }
    }

    this.indentOut();
    this.writeln('}');
    this.writeln('');

    // Also emit stand-alone items
    for (const child of node.body) {
      if (child.kind !== 'InstructionDeclaration') {
        this.emitTopLevel(child);
      }
    }
  }

  // === Instruction Client Method ===

  private emitInstructionMethod(node: AST.InstructionDeclaration): void {
    const methodName = this.toCamelCase(node.name);
    const params: string[] = [];

    for (const acc of node.accounts) {
      params.push(`${acc.name}: PublicKey`);
    }
    for (const p of node.params) {
      params.push(`${p.name}: ${this.typeToTS(p.type)}`);
    }

    this.writeln(`async ${methodName}(${params.join(', ')}): Promise<string> {`);
    this.indentIn();
    this.writeln(`const tx = await this.program.methods`);
    this.indentIn();
    const args = node.params.map(p => p.name).join(', ');
    this.writeln(`.${this.toCamelCase(node.name)}(${args})`);
    this.writeln('.accounts({');
    this.indentIn();
    for (const acc of node.accounts) {
      this.writeln(`${acc.name},`);
    }
    this.indentOut();
    this.writeln('})');
    this.writeln('.rpc();');
    this.indentOut();
    this.writeln('return tx;');
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Standalone Instruction Client ===

  private emitInstructionClient(node: AST.InstructionDeclaration): void {
    this.emitInstructionMethod(node);
  }

  // === Account / Struct Interface ===

  private emitAccountInterface(node: AST.AccountDeclaration): void {
    this.writeln(`export interface ${node.name} {`);
    this.indentIn();
    for (const field of node.fields) {
      this.writeln(`${field.name}: ${this.typeToTS(field.type)};`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  private emitInterface(node: AST.StructDeclaration): void {
    this.writeln(`export interface ${node.name} {`);
    this.indentIn();
    for (const field of node.fields) {
      this.writeln(`${field.name}: ${this.typeToTS(field.type)};`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Enum ===

  private emitTypeEnum(node: AST.EnumDeclaration): void {
    this.writeln(`export enum ${node.name} {`);
    this.indentIn();
    for (let i = 0; i < node.variants.length; i++) {
      this.writeln(`${node.variants[i].name} = ${i},`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Function ===

  private emitFunction(node: AST.FunctionDeclaration): void {
    const vis = node.visibility === 'pub' ? 'export ' : '';
    const asyncStr = node.isAsync ? 'async ' : '';
    const params = node.params.map(p => `${p.name}: ${this.typeToTS(p.type)}`).join(', ');
    const ret = node.returnType ? `: ${this.typeToTS(node.returnType)}` : '';

    this.writeln(`${vis}${asyncStr}function ${this.toCamelCase(node.name)}(${params})${ret} {`);
    this.indentIn();
    this.emitStatements(node.body);
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Event ===

  private emitEventInterface(node: AST.EventDeclaration): void {
    this.writeln(`export interface ${node.name}Event {`);
    this.indentIn();
    for (const field of node.fields) {
      this.writeln(`${field.name}: ${this.typeToTS(field.type)};`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
  }

  // === Error ===

  private emitErrorEnum(node: AST.ErrorDeclaration): void {
    this.writeln(`export enum ${node.name} {`);
    this.indentIn();
    for (const variant of node.variants) {
      this.writeln(`${variant.name} = ${variant.code},`);
    }
    this.indentOut();
    this.writeln('}');
    this.writeln('');
    this.writeln(`export const ${node.name}Messages: Record<number, string> = {`);
    this.indentIn();
    for (const variant of node.variants) {
      this.writeln(`[${variant.code}]: '${variant.message}',`);
    }
    this.indentOut();
    this.writeln('};');
    this.writeln('');
  }

  // === Const ===

  private emitConst(node: AST.ConstDeclaration): void {
    const vis = node.visibility === 'pub' ? 'export ' : '';
    const ty = node.type ? `: ${this.typeToTS(node.type)}` : '';
    this.writeln(`${vis}const ${node.name}${ty} = ${this.exprToTS(node.value)};`);
  }

  // === Client Block ===

  private emitClientBlock(node: AST.ClientBlock): void {
    this.writeln(`// --- Client: ${node.name} ---`);
    this.emitStatements(node.body);
    this.writeln('');
  }

  // === Statements ===

  private emitStatements(stmts: AST.Statement[]): void {
    for (const stmt of stmts) {
      this.emitStatement(stmt);
    }
  }

  private emitStatement(stmt: AST.Statement): void {
    switch (stmt.kind) {
      case 'LetStatement': {
        const kw = stmt.mutable ? 'let' : 'const';
        const ty = stmt.type ? `: ${this.typeToTS(stmt.type)}` : '';
        const val = stmt.value ? ` = ${this.exprToTS(stmt.value)}` : '';
        this.writeln(`${kw} ${stmt.name}${ty}${val};`);
        break;
      }
      case 'ConstStatement': {
        const ty = stmt.type ? `: ${this.typeToTS(stmt.type)}` : '';
        this.writeln(`const ${stmt.name}${ty} = ${this.exprToTS(stmt.value)};`);
        break;
      }
      case 'ReturnStatement': {
        this.writeln(stmt.value ? `return ${this.exprToTS(stmt.value)};` : 'return;');
        break;
      }
      case 'IfStatement': {
        this.writeln(`if (${this.exprToTS(stmt.condition)}) {`);
        this.indentIn();
        this.emitStatements(stmt.then);
        this.indentOut();
        if (stmt.else) {
          this.writeln('} else {');
          this.indentIn();
          this.emitStatements(stmt.else);
          this.indentOut();
        }
        this.writeln('}');
        break;
      }
      case 'ForStatement': {
        this.writeln(`for (const ${stmt.variable} of ${this.exprToTS(stmt.iterable)}) {`);
        this.indentIn();
        this.emitStatements(stmt.body);
        this.indentOut();
        this.writeln('}');
        break;
      }
      case 'ExpressionStatement': {
        this.writeln(`${this.exprToTS(stmt.expression)};`);
        break;
      }
      default:
        this.writeln(`// TODO: stmt ${stmt.kind}`);
    }
  }

  // === Expressions ===

  private exprToTS(expr: AST.Expression): string {
    switch (expr.kind) {
      case 'NumberLiteral': return expr.raw;
      case 'StringLiteral': return `'${expr.value}'`;
      case 'BooleanLiteral': return expr.value ? 'true' : 'false';
      case 'NullLiteral': return 'null';
      case 'IdentifierExpr': return expr.name;
      case 'BinaryExpr': return `(${this.exprToTS(expr.left)} ${expr.operator} ${this.exprToTS(expr.right)})`;
      case 'UnaryExpr': return `${expr.operator}${this.exprToTS(expr.operand)}`;
      case 'CallExpr': {
        const args = expr.args.map(a => this.exprToTS(a)).join(', ');
        return `${this.exprToTS(expr.callee)}(${args})`;
      }
      case 'MemberExpr': return `${this.exprToTS(expr.object)}.${expr.property}`;
      case 'IndexExpr': return `${this.exprToTS(expr.object)}[${this.exprToTS(expr.index)}]`;
      case 'ArrayExpr': {
        const elems = expr.elements.map(e => this.exprToTS(e)).join(', ');
        return `[${elems}]`;
      }
      case 'StructInitExpr': {
        const fields = expr.fields.map(f => `${f.name}: ${this.exprToTS(f.value)}`).join(', ');
        return `{ ${fields} }`;
      }
      case 'AwaitExpr': return `await ${this.exprToTS(expr.expression)}`;
      case 'SolLiteral': return `new BN(${expr.amount * 1_000_000_000})`;
      case 'LamportsLiteral': return `new BN(${expr.amount})`;
      default: return `/* TODO: expr ${expr.kind} */`;
    }
  }

  // === Type Mapping ===

  private typeToTS(type: AST.TypeAnnotation): string {
    switch (type.kind) {
      case 'PrimitiveType': {
        const map: Record<string, string> = {
          'u8': 'number', 'u16': 'number', 'u32': 'number', 'u64': 'BN',
          'u128': 'BN', 'i8': 'number', 'i16': 'number', 'i32': 'number',
          'i64': 'BN', 'i128': 'BN', 'f32': 'number', 'f64': 'number',
          'bool': 'boolean', 'string': 'string', 'pubkey': 'PublicKey', 'bytes': 'Buffer',
        };
        return map[type.name] ?? type.name;
      }
      case 'NamedType': {
        if (type.typeArgs && type.typeArgs.length > 0) {
          const args = type.typeArgs.map(a => this.typeToTS(a)).join(', ');
          return `${type.name}<${args}>`;
        }
        return type.name;
      }
      case 'ArrayType': return `${this.typeToTS(type.element)}[]`;
      case 'OptionType': return `${this.typeToTS(type.inner)} | null`;
      case 'TupleType': return `[${type.elements.map(e => this.typeToTS(e)).join(', ')}]`;
      default: return 'unknown';
    }
  }

  // === Utilities ===

  private toCamelCase(s: string): string {
    return s.replace(/(^|_)([a-z])/g, (_m, _p1, p2, offset: number) =>
      offset === 0 ? p2 : p2.toUpperCase()
    );
  }

  private toPascalCase(s: string): string {
    return s.replace(/(^|_)([a-z])/g, (_m, _p1, p2) => p2.toUpperCase());
  }

  private writeln(line: string): void {
    this.output.push('  '.repeat(this.indent) + line);
  }

  private indentIn(): void { this.indent++; }
  private indentOut(): void { this.indent = Math.max(0, this.indent - 1); }
}
